/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2018-06-26 15:12:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
String name=(String)session.getAttribute("currName");
if(name==null){
	session.setAttribute("errmsg", "Login First");
	request.getRequestDispatcher("/Login.jsp").forward(request, response);
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("h1{\r\n");
      out.write("\tfont-family: 'Montserrat',sans-serif;\r\n");
      out.write("\tfont-size:50px;\r\n");
      out.write("\tfont-weight:400;\r\n");
      out.write("\tletter-spacing: -1px;\r\n");
      out.write("\t\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("\tborder: 1px solid gray;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd {\r\n");
      out.write("    border-width: 1px;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    border-style: solid;\r\n");
      out.write("    border-color: #666666;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\tth {\r\n");
      out.write("    border-width: 1px;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    border-style: solid;\r\n");
      out.write("    border-color: #666666;\r\n");
      out.write("    background-color: #dedede;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"]{\r\n");
      out.write("font-size:1em;\r\n");
      out.write("height:2.3em;\r\n");
      out.write("border-radius:4px;\r\n");
      out.write("border:1px solid #c8cccf;\r\n");
      out.write("color:#6a6f77;\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"submit\"]{\r\n");
      out.write("font-size:1em; \r\n");
      out.write("height:2.3em;\r\n");
      out.write("border-radius:10px; \r\n");
      out.write("border:1px solid #c8cccf;设置输入框边框的粗细和颜色\r\n");
      out.write("color:#6a6f77; 设置输入框中文字的颜色\r\n");
      out.write("outline:0; 将输入框点击的时候出现的边框去掉\r\n");
      out.write("text-align:center; 设置输入框中文字的位置\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  <script language=\"javascript\">\r\n");
      out.write("        function mycheck(){\r\n");
      out.write("  if(document.getElementByName(\"addid\").value==\"\"){\r\n");
      out.write("  alert(\"用户名不能为空\");\r\n");
      out.write("  return false;\r\n");
      out.write("  }\r\n");
      out.write("  }\r\n");
      out.write("     </script>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'add.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("  \r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body background=\"BackgroundImage.jpg\">\r\n");
      out.write("  ");

   
      out.write("\r\n");
      out.write("  <h1 align=\"center\">欢迎添加学生</h1>\r\n");
      out.write("<input type = \"button\" style=\"font-size:1.4em; color:#000000;padding:10px;border-radius: 5px;\"value = \"返回\" onclick = \"window.location.href = 'StudentListServlet'\">\r\n");
      out.write("     </br>\r\n");
      out.write("     </br>\r\n");
      out.write("     <table>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<th>id</th>\r\n");
      out.write("    \t\t<th>学号</th>\r\n");
      out.write("    \t\t<th>姓名</th>\r\n");
      out.write("    \t\t<th>性别</th>\r\n");
      out.write("    \t\t<th>年龄</th>\r\n");
      out.write("    \t\t<th>专业</th>\r\n");
      out.write("    \t\t<th>操作</th>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<form onSubmit=\"return mycheck();\" action=\"StudentAddServlet\" method=\"get\" >\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t\t<td><input type=\"text\" name=\"addid\" /></td>\r\n");
      out.write("        \t\t\t<td><input type=\"text\" name=\"addstuno\" /></td>\r\n");
      out.write("        \t\t\t<td><input type=\"text\" name=\"addname\" /></td>\r\n");
      out.write("        \t\t\t<td><input type=\"text\" name=\"addsex\" /></td>\r\n");
      out.write("        \t\t\t<td><input type=\"text\" name=\"addage\" /></td>\r\n");
      out.write("        \t\t\t<td><input type=\"text\" name=\"addmajor\" /></td>\r\n");
      out.write("        \t\t\t<td><input onClick=\"return mycheck()\" type=\"submit\" value=\"添加\"/></td>\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t\t</form>\r\n");
      out.write("    </table>\r\n");
      out.write("    </br>\r\n");
      out.write("    <div align=\"center\"><input type = \"button\" style=\"font-size:1.4em; color:#000000;padding:10px 40px;border-radius: 5px;\"value = \"重置\" onclick = \"window.location.href = 'add.jsp'\"></div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
