/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2018-06-24 16:02:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.zr.entity.Student;
import java.util.*;
import java.io.*;

public final class stulist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\ttable{\r\n");
      out.write("\tborder: 1px solid gray;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd{\r\n");
      out.write("\tborder: 1px solid gray;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t");

	//从request中取出集合
	List<Student> list = (List<Student>)request.getAttribute("students");
	
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  <a href=\"add.jsp\"style=\"display: block; text-align: center;\">不如添加一个仙人？点我！</a>\r\n");
      out.write("    <table>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td>学号</td>\r\n");
      out.write("    \t\t<td>姓名</td>\r\n");
      out.write("    \t\t<td>性别</td>\r\n");
      out.write("    \t\t<td>年龄</td>\r\n");
      out.write("    \t\t<td>操作</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t");

    	if(list != null){
    		for(Student s : list){ 
        		
      out.write("\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t\t<td>");
      out.print(s.getStuno() );
      out.write("</td>\r\n");
      out.write("        \t\t\t<td>");
      out.print(s.getName() );
      out.write("</td>\r\n");
      out.write("        \t\t\t<td>");
      out.print(s.getGender() );
      out.write("</td>\r\n");
      out.write("        \t\t\t<td>");
      out.print(s.getAge() );
      out.write("</td>\r\n");
      out.write("        \t\t\t<td><a href=\"StudentDelServlet?id=");
      out.print(s.getId() );
      out.write("\">删除</a>\r\n");
      out.write("        \t\t<a href=\"Change.jsp?id=");
      out.print(s.getId() );
      out.write("\">修改</a>\t\r\n");
      out.write("        \t\t\t</td>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t\t");

        	}
    	}
    	
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
